### ISSUE TITLE
Malware detected in AvalonEdit 6.1.1.dll

### ISSUE THREAD

**Issue by sager** [icsharpcode/AvalonEdit#283] opened 2021-05-13 08:18 UTC
McAfee, AVG and Avast warn that in version 6.1.1 there is a malware included, you can check it here by uploading dll:
https://www.virustotal.com/gui/

**Comment by christophwille** [comment] 2021-05-13 08:21
https://www.virustotal.com/gui/file/366476e8fe9e9ccb777a225c2c1356ffd506c978d807b9e95189ee2ca23bf6c4/detection

**Comment by sager** [comment] 2021-05-13 08:48
Here is with .dll
https://www.virustotal.com/gui/file/86ff97015da0c2802b1c1c35d4e9c3c21cb024258557eff9cade16a9d58bd34b/detection

**Comment by christophwille** [comment] 2021-05-13 08:55
Seems like as usual crappy anti-virus software.

**Comment by siegfriedpammer** [comment] 2021-05-13 09:09
"FileRepMalware" is an indication that the file has low reputation according to https://forum.avast.com/index.php?topic=124265.msg941128#msg941128. So as AvalonEdit is not as commonly used as other libraries the AV does not know about it.

The other detection labelled "Artemis" is a similar reputation system, so, the problem is that AV software does not know about AvalonEdit.

@christophwille maybe it is necessary to upload AvalonEdit.dll in addition to the nupkg to let AV software learn about it in future?

virustotal is unfortunately not very useful if a signature is detected, as there is no information, as to what part of the binary causes suspicions. I can only say that we carefully inspect any pull requests.

**Comment by christophwille** [comment] 2021-05-13 09:13
The only thing we can do to "up" the reputation is to sign the binary like we do with ilspy.exe (but alas we do not sign icsharpcode.decompiler.dll in the nupkg)

**Comment by christophwille** [comment] 2021-05-15 09:22
Interesting tidbit: https://github.com/icsharpcode/ILSpy/blob/master/packages.props#L15 that doesn't seem to have helped the reputation (ILSpy does included AE latest, and ILSpy is used quite a bit so actually those scanners should flag an ILSpy installation)

**Comment by christophwille** [comment] 2021-05-20 13:23
I uploaded the assemblies in the 6.1.1 nupkg one-by-one to VT. Interestingly, neither net40 nor netcoreapp3.0 are being flagged, only the net45 one.

**Comment by christophwille** [comment] 2021-05-20 14:22
The code signing option

In ILSpy this is a (local) manual process for ilspy.exe only, with an OSS code signing cert from Certum. So we'd need to step up to Cloud (which is still cheap at Certum but doesn't give us a lot of benefits compared to "normal" EV certificates). We'd need to adapt the build automation (eg only signing master builds).

I am not sold on this approach because of a false positive from AV (in what - ten years of publishing this NuGet)

**Comment by christophwille** [comment] 2021-05-22 10:59
To document this further:

https://github.com/Dana-Woo/code-sign-action would be a way to get it off the ground, however, it would need to be based on a branch-protected environment for master (so no PR could ever touch the secrets)

**Comment by christophwille** [comment] 2021-05-22 11:57
Won't fix.

**Closed by christophwille** 2021-05-22 11:57 UTC
Labels: Area-Build, Issue-Question
